### PR TITLE
chore: update site dependencies

### PR DESCRIPTION
**Pull request by aureamunoz**
This updates jekyll site dependencies and should fix some dependabot alerts.

### CODE REVIEW

**Review by Sgitario — CHANGES_REQUESTED** [review]
I'm trying to rebuild the site from localhost by doing:

```
cd docs
bundle update
bundle exec jekyll serve
```

But the last command didn't work because some missing gems:

```
jcarvaja@localhost docs]$ bundle exec jekyll serve
Ignoring commonmarker-0.23.4 because its extensions are not built. Try: gem pristine commonmarker --version 0.23.4
Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
Ignoring http_parser.rb-0.8.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.8.0
Ignoring racc-1.6.0 because its extensions are not built. Try: gem pristine racc --version 1.6.0
Could not find commonmarker-0.23.4, racc-1.6.0, http_parser.rb-0.8.0 in any of the sources
Run `bundle install` to install missing gems.
```

Moreover, the instructions in https://github.com/dekorateio/dekorate/blob/main/docs/README.md are not fully accurated:
1. In the step "4. Clone your fork ", it says the repo is "git@github.com:YOUR_USER_NAME/community-theme.git" when it should be "git@github.com:YOUR_USER_NAME/dekorate.git"
2. In the step "5. Change into the project directory", it mentions "cd community-theme", when it should be "cd dekorate/docs"

If I'm doing something wrong, the same README file should clearly say the steps to serve the wiki locally.

**Comment by aureamunoz** [comment]
Yes, you're right, the readme is not correct. Could you please try: 
```
bundle install
bundle exec jekyll serve
```

**Comment by Sgitario** [comment]
> Yes, you're right, the readme is not correct. Could you please try:
> 
> ```
> bundle install
> bundle exec jekyll serve
> ```

I've just tried it and same error:

```
[jcarvaja@localhost docs]$ bundle exec jekyll serve
Ignoring commonmarker-0.23.4 because its extensions are not built. Try: gem pristine commonmarker --version 0.23.4
Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
Ignoring http_parser.rb-0.8.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.8.0
Ignoring racc-1.6.0 because its extensions are not built. Try: gem pristine racc --version 1.6.0
Could not find commonmarker-0.23.4, racc-1.6.0, http_parser.rb-0.8.0 in any of the sources
Run `bundle install` to install missing gems.
```

**Review by iocanel — APPROVED** [review]
LGTM

**Pull request merged**
