### PR TITLE
fix: populate Dekorate docker group and version from system properties

### PR DESCRIPTION
**Pull request by Sgitario**
Additionally, I've changed the annotation `@EnableDockerBuild` to `@DockerBuild` that was renamed in Dekorate 2.x.

Fix https://github.com/dekorateio/dekorate/issues/963

### CODE REVIEW

**Review by cmoulliard — COMMENTED** [review]
I did a test where I passed the version parameter and the result was wrong as the version tagged is `2.9-SNAPSHOT`
```
mvn clean install -Ddekorate.build=true -Ddekorate.docker.group=halkyonio -Ddekorate.docker.registry=ghcr.io -Ddekorate.docker.version=1.0
...
[INFO] Built image to Docker daemon as ghcr.io/halkyonio/spring-boot-on-kubernetes-with-jib-example:2.9-SNAPSHOT
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.941 s
[INFO] Finished at: 2022-05-03T10:46:10+02:00
[INFO] ------------------------------------------------------------------------
```

We have also the same issue using `mvn clean install -Ddekorate.build=true -Ddekorate.docker.image=ghcr.io/halkyonio/spring-boot-example:1.0`
-->
```
[INFO] Loading to Docker daemon...
[INFO] 
[INFO] Built image to Docker daemon as cmoullia/spring-boot-on-kubernetes-with-jib-example:2.9-SNAPSHOT
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by cmoulliard** [comment]
I did a test top of the commit `ebe8351c` and here is the result
```
OK  - mvn clean install -Ddekorate.build=true -Ddekorate.docker.group=halkyonio -Ddekorate.docker.registry=ghcr.io
OK  - mvn clean install -Ddekorate.build=true -Ddekorate.docker.group=halkyonio -Ddekorate.docker.registry=ghcr.io -Ddekorate.docker.version=1.0
NOK - mvn clean install -Ddekorate.build=true -Ddekorate.docker.image=ghcr.io/halkyonio/spring-boot-example:1.0
```

**Comment by Sgitario** [comment]
> I did a test top of the commit `ebe8351c` and here is the result
> 
> ```
> OK  - mvn clean install -Ddekorate.build=true -Ddekorate.docker.group=halkyonio -Ddekorate.docker.registry=ghcr.io
> OK  - mvn clean install -Ddekorate.build=true -Ddekorate.docker.group=halkyonio -Ddekorate.docker.registry=ghcr.io -Ddekorate.docker.version=1.0
> NOK - mvn clean install -Ddekorate.build=true -Ddekorate.docker.image=ghcr.io/halkyonio/spring-boot-example:1.0
> ```
> 
> **NOTE**: If `dekorate.docker.image` is not longer supported, then this documentation page should be reviewed: https://dekorate.io/configuration-guide/#docker and also include an example part of the Description to explain what a group, registry are with same example.

This issue is only about allowing docker group and version properties to be set via system properties. These properties and also the docker registry property explicitly says in the docker documentation that can be set via system properties. 
In Dekorate, the rest of the properties (including docker image), unless is not mentioned in the documentation, cannot be set via system properties. So I don't think we should mention anything special for it. 

What could be good is to add a new column "can be set via system property or similar" in all the configuration tables to let users when we can set a property via system property. In any case, if we want to do this, this should be done in a separated issue.

**Comment by cmoulliard** [comment]
> What could be good is to add a new column "can be set via system property or similar" in all the configuration tables to let users when we can set a property via system property

Good idea. I still dont understand by the way why we can set some properties as properties file or annotations and not  as `-Ddekorate.x.y.`. Can you explain ? @Sgitario

**Comment by Sgitario** [comment]
> > What could be good is to add a new column "can be set via system property or similar" in all the configuration tables to let users when we can set a property via system property
> 
> Good idea. I still dont understand by the way why we can set some properties as properties file or annotations and not as `-Ddekorate.x.y.`. Can you explain ? @Sgitario

I've already created https://github.com/dekorateio/dekorate/issues/965 to do this.

**Review by iocanel — APPROVED** [review]
LGTM

**Review by cmoulliard — APPROVED** [review]

**Pull request merged**
