### PR TITLE
feat: autogenerate dekorate-bom and dekorate-spring-bom.

### PR DESCRIPTION
**Pull request by iocanel**
----

#

### CODE REVIEW

**Comment by geoand** [comment]
Not sure how I can review it :p

**Comment by aureamunoz** [comment]
Same here!!

**Comment by iocanel** [comment]
@geoand, @aureamunoz : You can you the Al Pacino rule: "When i doubt .... Approve!"

**Comment by geoand** [comment]
I was going to use my rule: `I trust team members to do the right thing` :)

**Pull request merged**
