### PR TITLE
Include only the fabric8 resources for model in the apt dependencies

### PR DESCRIPTION
**Pull request by Sgitario**
Relates to https://github.com/quarkusio/quarkus/pull/30480

### CODE REVIEW

**Review by iocanel — CHANGES_REQUESTED** [review]
We can't completely remove these lines, and still keep around: https://github.com/dekorateio/dekorate/blob/main/annotations/servicebinding-annotations/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.model.KubernetesResource

We either need to remove both, or keep an entry like:
```xml
<include>META-INF/services/io.fabric8.kubernetes.api.model.KubernetesResource</include>
```

I am not sure however, if this is something we still use or it need also go away. Waiting for @manusa to clarify.

**Comment by Sgitario** [comment]
> We can't completely remove these lines, and still keep around: https://github.com/dekorateio/dekorate/blob/main/annotations/servicebinding-annotations/src/main/resources/META-INF/services/io.fabric8.kubernetes.api.model.KubernetesResource
> 
> We either need to remove both, or keep an entry like:
> 
> ```
> <include>META-INF/services/io.fabric8.kubernetes.api.model.KubernetesResource</include>
> ```
> 
> I am not sure however, if this is something we still use or it need also go away. Waiting for @manusa to clarify.

Ups, sorry, my bad. I've already corrected the pull request. 
Please, @manusa confirm you're ok with these changes too.

**Comment by manusa** [comment]
This is used by the `KubernetesDeserializer` to detect the different model types

https://github.com/fabric8io/kubernetes-client/blob/97f53c71d275e7544c7d757cc0fecb3fb0889109/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/internal/KubernetesDeserializer.java#L194

https://github.com/fabric8io/kubernetes-client/pull/4511

**Review by manusa — APPROVED** [review]
Changes seem fine, thx

**Review by iocanel — APPROVED** [review]
lgtm

**Pull request merged**
