### PR TITLE
Kubernetes HostAliases property

### PR DESCRIPTION
**Pull request by Vinche59**
Allow the generation of hostAliases property from Deployment

Signed-off-by: Vincent Sourtin <sourin-v@bridgestone-bae.com>

### CODE REVIEW

**Review by iocanel — APPROVED** [review]
Looks awesome!
Thank you very much!

**Comment by Vinche59** [comment]
@iocanel Thanks for merging it 👍
Eventually, I will need it to work with Quarkus (which seems to use 0.12.x branch at the moment). 
Do I have also make a pull request for that branch as, with the use of dekorate-dependencies, some imports have to be changed ?

**Comment by iocanel** [comment]
Usually I cherry pick myself. But a or for 0.12.x would be awesome.

**Comment by Vinche59** [comment]
Done.
Thanks you for all your work here.

**Pull request merged**
