### PR TITLE
Refactor integration tests into independant modules (#324).

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by geoand** [comment]
This is the one @metacosm really wanted :)

I like it as well of course :P

**Comment by iocanel** [comment]
> This is the one @metacosm really wanted :)
> 
> I like it as well of course :P

**Comment by geoand** [comment]
Hm... Shouldn't the openshift tests have been run as well?

CI seems to show only one job was executed

**Comment by iocanel** [comment]
> Hm... Shouldn't the openshift tests have been run as well?
> 
> CI seems to show only one job was executed

All jobs run fine.

**Comment by geoand** [comment]
OK nevermind. I had to look at the details page whereas I used to be able to see them all in the PR page

**Pull request merged**
