### PR TITLE
Cleanup generated YAML

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@iocanel let me know when you do a release so we can pick it up in Quarkus and close the issue there as well.

**Comment by iocanel** [comment]
@geoand: I'll release later today at box o'clock!

**Comment by geoand** [comment]
Excellent!

**Comment by geoand** [comment]
@iocanel do we now have a release that contains this?

**Comment by iocanel** [comment]
@geoand: It's should be part of 0.12.1

**Comment by geoand** [comment]
Excellent. I'll send a PR to bump the version in Quarkus.

**Pull request merged**
