### PR TITLE
fix (#442): Bound name, group, version and labels per platform and

### PR DESCRIPTION
**Pull request by iocanel**
don't have global values for them.

### CODE REVIEW

**Comment by geoand** [comment]
Shouldn't we have new tests for this?

**Comment by iocanel** [comment]
> Shouldn't we have new tests for this?

**Comment by geoand** [comment]
Ok cool 👍

**Comment by iocanel** [comment]
> LGTM, I am only requesting changes so we can get the tests and not merge by accident without them

Tests have been added!

**Pull request merged**
