### PR TITLE
chore: update orb to 0.4.0

### PR DESCRIPTION
**Pull request by aureamunoz**

### CODE REVIEW

**Comment by aureamunoz** [comment]
WDYT @iocanel @metacosm ?

**Comment by metacosm** [comment]
I don't really have an opinion on this. Do we really need that update? What does it bring that the current version doesn't?

**Comment by aureamunoz** [comment]
I don't know exactly but there is only one tag 0.4.0 so thought it would be good idea to use this one? 
https://github.com/snowdrop/circleci-orbs/tags

**Review by iocanel — APPROVED** [review]
LGTM

**Pull request merged**
