### PR TITLE
add servicebinding support

### LINKED ISSUE #678: Add Dekorate ServiceBinding Annotation processor

### PR DESCRIPTION
**Pull request by yharish991**
Resolves #678 #679 #680 #681

### CODE REVIEW

**Review by iocanel — APPROVED** [review]

**Comment by yharish991** [comment]
@iocanel can this be merged?

**Comment by iocanel** [comment]
> @iocanel can this be merged?

Merged! Congratulations!

**Comment by yharish991** [comment]
thanks @iocanel :) , what is the procedure to cut a release for this?

**Comment by iocanel** [comment]
I'll cut one later today!

**Pull request merged**
