### PR TITLE
Prepare for 2.0.0

### PR DESCRIPTION
**Pull request by iocanel**
This pull request does the following:
- makes all examples standalone (no parent)
- algin naming in examples
- align naming in tests

### CODE REVIEW

**Comment by iocanel** [comment]
cc @wtrocki 
The intention here is that the examples in each branch are meant to run with the release version corresponding to that branch.
So, the examples of master will be always compatible with the latest release (once we get 2.0.0) out.

**Comment by iocanel** [comment]
@geoand @metacosm: I just need a quick review, before I cut 2.0.0.beta1

**Review by geoand — APPROVED** [review]
Too long - didn't read :)

Tests are passing and I am sure that if there are any issues, they will show up when you cut the release

**Comment by metacosm** [comment]
Yeah, pretty much the same as @geoand  😄

**Pull request merged**
