### PR TITLE
fix (#788): Enable POSIX long file mode.

### PR DESCRIPTION
**Pull request by iocanel**

### CODE REVIEW

**Comment by aureamunoz** [comment]
I'm on it!

**Comment by iocanel** [comment]
> I'm on it!

Thanks

**Comment by aureamunoz** [comment]
Unfortunately, it doesn't work @iocanel , when we use the `TarArchiveOutputStream.BIGNUMBER_POSIX` the max accepted value is : `TarConstants.MAXID`= 2097151. We can see it in the logs also: 

```
[ERROR] Caused by: java.lang.IllegalArgumentException: group id '1000690000' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit
[ERROR] at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:651)
[ERROR] at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumberWithPosixMessage(TarArchiveOutputStream.java:644)
[ERROR] at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:626)
[ERROR] at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:377)
[ERROR] at io.dekorate.utils.Packaging.putTarEntry(Packaging.java:142)
[ERROR] at io.dekorate.utils.Packaging$1.visitFile(Packaging.java:124)
[ERROR] at io.dekorate.utils.Packaging$1.visitFile(Packaging.java:100)
[ERROR] at java.base/java.nio.file.Files.walkFileTree(Files.java:2725)
[ERROR] at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)
[ERROR] at io.dekorate.utils.Packaging.packageFile(Packaging.java:100)
[ERROR] at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:323)
```

**Comment by iocanel** [comment]
@aureamunoz: I updated the PR as per @cmoulliard recommendation. Please let me know if this fixes your issue, cause I am hoping for a release soon.

**Review by aureamunoz — APPROVED** [review]
It works. It should be fine to have a test case but it's not easy to have an uid/gid as big as the error requires.......
Once released, we need to update Quarkus to use this fix because the Quarkus OpenShift extension fails if the gid/uid > 2097151.

**Pull request merged**
