### PR TITLE
fix: always generate buildconfig as long as we have proper git info

### LINKED ISSUE #292: buildConfig should not be generated by default
Since we use the `deploymentMode = dev` mode by default we shouldn't generate the build config by default.

that's what it's generated from a scaffolded project for example:
```
buildConfig:
      type: "s2i"
      url: null
      ref: "master"
      contextPath: ""
      moduleDirName: "foo"
```
That doesn't make sense, buildConfig should not be generated.

### PR DESCRIPTION
**Pull request by metacosm**
Reverts fix of #292

### CODE REVIEW

**Comment by geoand** [comment]
LGTM

**Comment by geoand** [comment]
tests failed :(

**Comment by cmoulliard** [comment]
Why does it fail ?

**Comment by geoand** [comment]
```
[INFO] Running io.dekorate.examples.ComponentSpringBootExampleTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.315 s <<< FAILURE! - in io.dekorate.examples.ComponentSpringBootExampleTest
[ERROR] shouldContainComponentWithDefaultValues  Time elapsed: 0.306 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <null> but was: <io.dekorate.halkyon.model.BuildConfig@2177849e>
```

**Pull request merged**
