### PR TITLE
Add prefix to env

### LINKED ISSUE #1288: Support env vars from secrets with a prefix
Actually to solve the issue on https://github.com/quarkusio/quarkus/issues/38604, we need to provide a way to use prefix on `io.dekorate.kubernetes.config.EnvBuilder`.

### PR DESCRIPTION
**Pull request by mcruzdev**
Fixes #1288

### CODE REVIEW

**Comment by mcruzdev** [comment]
Hi @iocanel this is the only thing that we need to change, makes sense?

**Comment by mcruzdev** [comment]
Hi @iocanel, I made some progess with this task, can you review it?

**Review by iocanel — APPROVED** [review]
LGTM

**Comment by mcruzdev** [comment]
Hi @iocanel, TY! This is a flaky test?

**Comment by iocanel** [comment]
Let me re-run them one more time.

**Pull request merged**
