### PR TITLE
refactor: move methods and harmonize signatures. Related to #295

### PR DESCRIPTION
**Pull request by aureamunoz**
I spent a little time trying to refactor this methods in order to extract some common code between them but finally I find myself rewriting a code very similar to existing one. So I end up by moving the methods to the Maps utility class and harmonize their signatures with the Maps.fromProperties one.
WDYT @iocanel ? Leave yours thoughts here but let's keep the Draft :point_down: 

For info, I'm going to do a presentation to a spanish customer about how to contribute to an opensource project and I will do a live code demo. I would like to do this modification because it's a `low-hanging-fruit` and I think it's good for a first contribution so please @iocanel don't approuve this PR in order to make it during my demo.

### CODE REVIEW

**Comment by iocanel** [comment]
@aureamunoz Thanks for the heads up! My intention is to keep it a draft anyway, as I am in the middle of a huge refactor and I'd like to merge this afterr its done.

**Comment by iocanel** [comment]
@aureamunoz: should we merge this now, or you still want it as an open PR?

**Comment by aureamunoz** [comment]
Let's wait a little more because I'm going to do the demo again the week of 21th of September!

**Comment by aureamunoz** [comment]
We can merge this now if you want @iocanel (once the checks pass of course)

**Comment by aureamunoz** [comment]
checks passed! When you have some spare time I will be happy to have your review @iocanel . Thanks :-)

**Review by iocanel — APPROVED** [review]
LGTM, but needs a rebase.

**Comment by aureamunoz** [comment]
Done! Let's see what CI says

**Pull request merged**
