### PR TITLE
Fix halkyon packaging

### LINKED ISSUE #320: Add a halkyon starter for easier dependency management

### PR DESCRIPTION
**Pull request by metacosm**
Should also fix #320

### CODE REVIEW

**Comment by geoand** [comment]
I wonder why CI wasn't triggered...

**Comment by geoand** [comment]
Closed and reopened to try and trigger CI

**Comment by cmoulliard** [comment]
LGTM

**Comment by geoand** [comment]
@metacosm can you try pushing a change to the PR to see if CI will wake up?

**Pull request merged**
